name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Checks 0C and 32F
      id: checks-0c-and-32f
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Checks 0C and 32F
        setup-command: ''
        command: javac src/Main.java && java -cp src Main
        input: ''
        expected-output: |-
          0.0C is 32.0F
          32.0F is 0.0C
        comparison-method: contains
        timeout: 2
        max-score: 33
    - name: Checks 100C and 212F
      id: checks-100c-and-212f
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Checks 100C and 212F
        setup-command: sed -i 's/double testCelsius = .*/double testCelsius = 100.0;/'
          src/Main.java && sed -i 's/double testFahrenheit = .*/double testFahrenheit
          = 212.0;/' src/Main.java
        command: javac src/Main.java && java -cp src Main
        input: ''
        expected-output: |-
          100.0C is 212.0F
          212.0F is 100.0C
        comparison-method: contains
        timeout: 2
        max-score: 33
    - name: Checks -40C and -40F
      id: checks-40c-and-40f
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Checks -40C and -40F
        setup-command: sed -i 's/double testCelsius = .*/double testCelsius = -40.0;/'
          src/Main.java && sed -i 's/double testFahrenheit = .*/double testFahrenheit
          = -40.0;/' src/Main.java
        command: javac src/Main.java && java -cp src Main
        input: ''
        expected-output: |-
          -40.0C is -40.0F
          -40.0F is -40.0C
        comparison-method: contains
        timeout: 2
        max-score: 33
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECKS-0C-AND-32F_RESULTS: "${{steps.checks-0c-and-32f.outputs.result}}"
        CHECKS-100C-AND-212F_RESULTS: "${{steps.checks-100c-and-212f.outputs.result}}"
        CHECKS-40C-AND-40F_RESULTS: "${{steps.checks-40c-and-40f.outputs.result}}"
      with:
        runners: checks-0c-and-32f,checks-100c-and-212f,checks-40c-and-40f
